blank_issues_enabled: false
contact_links:
  - name: Ask a question
    about: Join our discord server to ask questions and discuss with maintainers and contributors.
    url: https://discord.gg/swqtb7AsNQ